salt_states: ./sample-salt
salt_pillar: ./sample-pillar
salt_master: test-admin-01
environment: lab
default_box: madeinpreston/carer7
default_memory: 2048
special_box:
 - host: test-admin-01
   box:  madeinpreston/carers7master
   memory: 1024
   mounts: [['./salt/salt/renderers','/renderers'],['./pass_data/gnupg','/root/.gnupg'],['./pass_data/password-store','/root/.password-store']]
 - host: test-web-01
   box:  madeinpreston/carer7
   memory: 512
 - host: test-web-02
   box:  madeinpreston/carer7
   memory: 512
exclude:
 - test-web-01
 - test-web-02
 - test-lab-01
